= QSNAP(8)
:doctype: manpage
:author: Thomas Schneider

== NAME
qsnap - A simple snapshot tool for BtrFS subvolumes

== SYNOPSIS
[verse]
*qsnap* '<subvolume>'

== DESCRIPTION
qsnap is a simple tool to create BtrFS subvolume snapshots, named after a
timestamp.

It is expected and assumed that all subvolumes are in the same directory
(defaults to '/mnt/root', adjustable in '/etc/qsnap.conf').  This may, but does
not have to be the root (subvolid 5) of the BtrFS filesystem.  The snapshots for
a subvolume are put in a directory next to it and named like the submodule plus
the suffix '.snapshots'.  In this directory, hierarchical subdirectories for
year (4 digits), month and day (2 digits each) are created.  The snapshot itself
is put into today’s directory and named 'YYYY-MM-DDTHH:MM+ZZZZ' (year, month, day,
hour, minute, timezone offset; as described in ISO 8601 and generated by 'date
-Im').

== FILES
'/etc/qsnap.conf'::
    * Must be valid shell syntax (will be sourced)
    * Should contain a single variable assignment:
+
[source,shell]
----
ROOT="/mnt/root"
----
    * May contain comments (starting with '#')

== SEE ALSO
'btrfs-subvolume(8)'

== AUTHOR AND LICENSE
'qsnap' was written by Thomas Schneider and is licensed under the ISC license.

== RESOURCES, BUGS, CONTRIBUTING
Bugs and Pull Requests to https://github.com/qsuscs/qsnap
