#!/bin/sh
#
# Copyright © 2015 Thomas Schneider <thosch97@gmail.com>
# Distributed under the terms of the ISC license, see LICENSE for details.
#

TIMEU=$(date +%s)
[ -f /etc/qsnap.conf ] && . /etc/qsnap.conf
: ${QSNAP_ROOT:=/mnt/root}
SVN="$1"

TIMEY=$(date -d@"${TIMEU}" +%Y)
TIMEM=$(date -d@"${TIMEU}" +%m)
TIMED=$(date -d@"${TIMEU}" +%d)
TIMES=$(date -d@"${TIMEU}" -Im)

cd "${QSNAP_ROOT}"
mkdir -p "${SVN}.snapshots/${TIMEY}/${TIMEM}/${TIMED}"
btrfs subvolume snapshot "${SVN}" "${SVN}.snapshots/${TIMEY}/${TIMEM}/${TIMED}/${TIMES}"
