#!/bin/sh
#
# Copyright © 2015 Thomas Schneider <thosch97@gmail.com>
# Distributed under the terms of the ISC license, see LICENSE for details.
#

time_U="$(date +%s)"
[ -f /etc/qsnap.conf ] && . /etc/qsnap.conf
: ${QSNAP_ROOT:=/mnt/root}
QSNAP_SVN="$1"

time_Y="$(date -d@"${time_U}" +%Y)"
time_M="$(date -d@"${time_U}" +%m)"
time_D="$(date -d@"${time_U}" +%d)"
time_S="$(date -d@"${time_U}" -Im)"

cd "${QSNAP_ROOT}"
mkdir -p "${QSNAP_SVN}.snapshots/${time_Y}/${time_M}/${time_D}"
btrfs subvolume snapshot "${QSNAP_SVN}" "${QSNAP_SVN}.snapshots/${time_Y}/${time_M}/${time_D}/${time_S}"
